chore(ci): tweak yaml indentation for zizmor's YAML parser
This change in indentation of multiple strings in YAML avoids this
limitation error with zizmor:

     INFO zizmor: 🌈 zizmor v1.25.2
    fatal: no audit was performed
    error: failed to load file://./.github/workflows/close-stale.yml as workflow
      |
      = help: this typically indicates a bug in zizmor; please report it
      = help: https://github.com/zizmorcore/zizmor/issues/new?template=bug-report.yml

    Caused by:
        0: failed to load file://./.github/workflows/close-stale.yml as workflow
        1: failed to load internal pathing document
        2: input is not valid YAML

Refs: https://github.com/zizmorcore/zizmor/issues/1116