chore(lint:deps): update knip version used for linting deps
This is also an attempt to mitigate this lint failure being hit in CI,
but not locally on macOS:

```
> opentelemetry-js-contrib@0.1.0 lint:deps
> npx --yes knip@5.33.3 --dependencies --production --tags=-knipignore

npm warn deprecated @snyk/github-codeowners@1.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
file:///home/runner/.npm/_npx/ac0927abb2277a89/node_modules/knip/dist/typescript/create-hosts.js:7
const libLocation = path.dirname(ts.getDefaultLibFilePath({}));
                                    ^

TypeError: ts.getDefaultLibFilePath is not a function
    at file:///home/runner/.npm/_npx/ac0927abb2277a89/node_modules/knip/dist/typescript/create-hosts.js:7:37
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)

Node.js v18.20.8
Error: Process completed with exit code 1.
```