fix(baggage-span-processor): cannot find module
Fixes the following error:
```
Error: Cannot find module '/Users/long/Repos/wise-rock/node_modules/@opentelemetry/baggage-span-processor/build/src/index.ts'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:415:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:665:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/long/Repos/wise-rock/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (/Users/long/Repos/wise-rock/node_modules/tsconfig-paths/src/register.ts:115:36)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/long/Repos/wise-rock/apps/api/src/tracing.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/long/Repos/wise-rock/node_modules/@opentelemetry/baggage-span-processor/package.json',
  requestPath: '@opentelemetry/baggage-span-processor'
}
```