avoid TS2775 typescript error during 'npm run compile'
Was getting compilation errors like this:

test/documentLoad.test.ts:264:7 - error TS2775: Assertions require every name in the call target to be declared with an explicit type annotation.

264       assert.ok(plugin instanceof DocumentLoadInstrumentation);
          ~~~~~~~~~

  test/documentLoad.test.ts:48:9
    48 const { assert } = chai as typeof import('chai');
               ~~~~~~
    'assert' needs an explicit type annotation.